spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/warehousedb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
  main:
    allow-bean-definition-overriding : true
feign:
  hystrix:
    enabled: true
