eureka:
  client:
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
spring:
  application:
    name: warehousehome
  datasource:
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/warehousedb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
  main:
    allow-bean-definition-overriding: true
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    cache: false
