spring:
  mail:
    host: smtp.qq.com
    port: 465
    username: 1326293136@qq.com
    password: xihuakiqzjgyiefj
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/warehousedb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      charset: UTF-8

